using System.Text;

namespace Polecat.CodeGeneration;

/// <summary>
///     Emits C# source for a typed document provider with pre-computed SQL strings.
///     The generated class provides compile-time SQL for CRUD operations,
///     eliminating the need for runtime string interpolation.
/// </summary>
internal static class DocumentProviderEmitter
{
    public static string Emit(DocumentClassInfo info)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.NamespaceName))
        {
            sb.AppendLine($"namespace {info.NamespaceName};");
            sb.AppendLine();
        }

        var tableName = info.TableName;
        var schema = "dbo"; // Default schema; runtime override handled by DocumentProvider

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"///     Auto-generated document provider for <see cref=\"{info.ClassName}\"/>.");
        sb.AppendLine($"///     Contains pre-computed SQL strings for CRUD operations.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {info.ClassName}DocumentProvider");
        sb.AppendLine("{");

        // Table name
        sb.AppendLine($"    public const string TableName = \"{tableName}\";");
        sb.AppendLine($"    public const string DefaultSchema = \"{schema}\";");
        sb.AppendLine($"    public const string DefaultQualifiedTableName = \"[{schema}].[{tableName}]\";");
        sb.AppendLine();

        // SQL Id type
        sb.AppendLine($"    public const string SqlIdType = \"{info.SqlIdType}\";");
        sb.AppendLine();

        // Select SQL
        sb.AppendLine($"    public const string SelectSql =");
        sb.AppendLine($"        \"SELECT id, data, version, last_modified, created_at, dotnet_type, tenant_id FROM [{schema}].[{tableName}]\";");
        sb.AppendLine();

        // Load SQL
        sb.AppendLine($"    public const string LoadSql =");
        sb.AppendLine($"        \"SELECT id, data, version, last_modified, created_at, dotnet_type, tenant_id FROM [{schema}].[{tableName}] WHERE id = @id AND tenant_id = @tenant_id;\";");
        sb.AppendLine();

        // Insert SQL (with MERGE for upsert)
        sb.AppendLine($"    public const string InsertSql =");
        sb.AppendLine($"        \"INSERT INTO [{schema}].[{tableName}] (id, data, version, last_modified, created_at, dotnet_type, tenant_id) \" +");
        sb.AppendLine($"        \"VALUES (@id, @data, 1, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), @dotnet_type, @tenant_id);\";");
        sb.AppendLine();

        // Upsert SQL (MERGE)
        sb.AppendLine($"    public const string UpsertSql =");
        sb.AppendLine($"        \"MERGE [{schema}].[{tableName}] AS target \" +");
        sb.AppendLine($"        \"USING (SELECT @id AS id, @tenant_id AS tenant_id) AS source \" +");
        sb.AppendLine($"        \"ON target.id = source.id AND target.tenant_id = source.tenant_id \" +");
        sb.AppendLine($"        \"WHEN MATCHED THEN UPDATE SET data = @data, version = target.version + 1, \" +");
        sb.AppendLine($"        \"last_modified = SYSDATETIMEOFFSET(), dotnet_type = @dotnet_type \" +");
        sb.AppendLine($"        \"WHEN NOT MATCHED THEN INSERT (id, data, version, last_modified, created_at, dotnet_type, tenant_id) \" +");
        sb.AppendLine($"        \"VALUES (@id, @data, 1, SYSDATETIMEOFFSET(), SYSDATETIMEOFFSET(), @dotnet_type, @tenant_id);\";");
        sb.AppendLine();

        // Delete SQL
        sb.AppendLine($"    public const string DeleteSql =");
        sb.AppendLine($"        \"DELETE FROM [{schema}].[{tableName}] WHERE id = @id AND tenant_id = @tenant_id;\";");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
