name: aspnetcore

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test-template.yml
    strategy:
      fail-fast: false
      matrix:
        storage_type: [default, edge]
        run: [1, 2, 3, 4, 5]   # repeat
    with:
      TEST_PROJECT_PATH: src/Polecat.AspNetCore.Testing/Polecat.AspNetCore.Testing.csproj
      STORAGE_TYPE: ${{ matrix.storage_type }}
