name: efcore-with-azure-sql-edge

on:
  push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-test-template:
    uses: ./.github/workflows/test-template.yml
    with:
      TEST_PROJECT_PATH: src/Polecat.EntityFrameworkCore.Tests/Polecat.EntityFrameworkCore.Tests.csproj
      USE_AZURE_SQL_EDGE: true